version: "3.9"
services:

  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 3s
      retries: 10
      interval: 5s
    volumes:
      - todolist_diplom_pg_data:/var/lib/postgresql/data/

  collect_static:
    build: .
    env_file: .env
    command: python manage.py collectstatic -c --no-input
    volumes:
      - django_static:/app/static/

  api:
    build: .
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres_db
      - DEBUG=False
    depends_on:
      postgres_db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app/core/
      - ./goals:/app/goals/
      - ./todolist_diplom:/app/todolist_diplom/

  run_migrations:
    build: .
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy
    command: python manage.py migrate

  front:
    image: sermalenk/skypro-front:lesson-38
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

  bot:
    build: .
    env_file: .env
    depends_on:
      postgres_db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/app/.env
    command: python manage.py runbot

volumes:
  todolist_diplom_pg_data:
  django_static: