version: "3.9"
services:
  #  front:
  #    image: sermalenk/skypro-front:lesson-34
  #    ports:
  #      - 8000:8000
  #    depends_on:
  #        api:
  #          condition: service_started

    run_migrations:
      build:
        context: .
      env_file: .env
      environment:
        POSTGRES_HOST: postgres_db
      depends_on:
        postgres_db:
          condition: service_healthy
      command: python manage.py migrate
#
    api:
      build: .
      env_file: .env
      environment:
        POSTGRES_HOST: postgres_db
      depends_on:
        postgres_db:
          condition: service_healthy
        run_migrations:
          condition: service_completed_successfully
      ports:
        - "8000:8000"
#      volumes:
#        - ./core:/app/core/
#        - ./todolist:/app/todolist

    postgres_db:
      image: postgres:15.1-alpine
      ports:
        - "5432:5432"
      #    env_file: .env
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB$: postgres
        POSTGRES_PASSWORD: postgres
      healthcheck:
        test: pg_isready -U postgres-d postgres
        timeout: 3s
        retries: 10
        interval: 5s
      volumes:
        - todolist_diplom_pg_data:/var/lib/postgresql/data/

volumes:
  todolist_diplom_pg_data:
