# Generated by Django 4.2.3 on 2023-07-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_title_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsModelMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(verbose_name='Дата последнего обновления')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='updated',
        ),
        migrations.AddField(
            model_name='goal',
            name='goalsmodelmixin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goals.goalsmodelmixin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalcategory',
            name='goalsmodelmixin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goals.goalsmodelmixin'),
            preserve_default=False,
        ),
    ]
