version: "3.9"
services:


  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 3s
      retries: 10
      interval: 5s
    volumes:
      - todolist_diplom_pg_data:/var/lib/postgresql/data/

  collect_static:
    image: ${DOCKERHUB_USER}/todolist_diplom:latest
    env_file: .env
    command: python manage.py collectstatic -c --no-input
    volumes:
      - django_static:/app/static/

  run_migrations:
    image: ${DOCKERHUB_USER}/todolist_diplom:latest
    env_file: .env
    depends_on:
      postgres_db:
        condition: service_healthy
    command: python manage.py migrate

  api:
    image: ${DOCKERHUB_USER}/todolist_diplom:latest
    env_file: .env
    depends_on:
      postgres_db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully

  front:
    image: sermalenk/skypro-front:lesson-35
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/





volumes:
  todolist_diplom_pg_data:
  django_static: